version: "3.9"
services:
  instagram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./followers.json:/app/followers.json
      - ./.env:/app/.env
    restart: always